[variables]
NODE_ENV = 'production'

[phases.setup]
nixpkgs = ['nodejs_18', 'python3', 'gcc', 'gnumake', 'pkg-config']

[phases.install]
cmds = [
  'cp backend/package*.json ./',
  'npm ci --only=production --no-audit --no-fund || npm install --omit=dev --no-audit --no-fund'
]

[phases.build]
cmds = ['cp -r backend/* ./']

[start]
cmd = 'node index.js'
