[phases.setup]
nixpkgs = ['nodejs_18', 'python3', 'gcc', 'gnumake', 'pkg-config']

[phases.install] 
cmds = [
  'cp backend/package*.json ./',
  'npm ci --only=production --no-audit --no-fund'
]

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'cp -r backend/* ./ && node index.js'

[variables]
NODE_ENV = 'production'
