services:
  - type: web
    name: api-monitoring-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: api-monitoring-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: ALERT_EMAIL_TO
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: MONITOR_INTERVAL
        value: 60000
      - key: DEFAULT_TIMEOUT
        value: 30000

databases:
  - name: api-monitoring-db
    plan: starter
